
sudo: required

language: java

jdk:
  - openjdk8

services:
  - docker

script: make docker

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push pkleindienst/jscheme
