
sudo: required

language: java

jdk:
  - openjdk8

services:
  - docker

script: make

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - | -
    curl -H "Content-Type: application/json" --data '{"docker_tag": "master"}' -X POST ${DOCKER_TRIGGER_URL}
